- name: Configure JBoss on infrastructure
  hosts: all
  tasks:
    - name: Show which OS family ansible is currently running on
      debug:
        var: ansible_facts['os_family']

    - name: Install JBoss if on Windows
      include_role:
        name: windows_jboss
      when: ansible_facts['os_family'] == "Windows"

    - name: Install JBoss if on RHEL
      include_role:
        name: rhel_jboss
      when: ansible_facts['os_family'] == "RedHat"

    # Similarly, we can install middleware on any OS by filtering
    # on the ansible_facts data which indicate the type of OS we are on.
    #- name: Install JBoss if on AIX
    #  include_role:
    #    name: rhel_jboss
    #  when: ansible_facts['os_family'] == "AIX"

      

